### ISSUE TITLE
#US2 - Éditer un article

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#1]
ETQ rédacteur je peux écrire un article afin de le mettre en forme

- [ ] ~~- doit afficher des outils : titre, gras, italique, barré, souligné, quote, liens interne/externe, liste, ancres~~
- [ ] ~~- doit comporter le glisser/déposer d'image et la sélection de fichiers~~
- [x] - doit afficher la langue
- [x] - doit permettre de prévisualiser l'article

**Comment by vinyll** [comment]
Editeurs possibles :
- https://simplemde.com/
- https://prosemirror.net/
- https://bevacqua.github.io/woofmark/
