### ISSUE TITLE
#US20 - Proposer un article

### ISSUE THREAD

**Issue by cafebabel** [cafebabel/cafebabel.com#10]
ETQ contributeur rédacteur, je veux proposer un article ou un pitch à cafébabel afin de partager mon opinion ou de témoigner d'un quotidien.

- [x] - doit permettre d'accéder à un formulaire (pitch form) depuis la homepage
- [x] - doit permettre de remplir les champs proposés : language*, topic*, angle, format, additional info, name*, contact email*, city, media, section
- [x] - doit comporter un bouton pour soumettre les informations
- [x] - doit permettre de soumettre les infos même sans être authentifié
- [x] -  doit notifier que les infos ont été envoyées
- [x] - doit comporter un lien vers un contact email vers une éditrice

**Comment by davidbgk** [comment]
@cafebabel-webmaster est-ce que le contributeur/rédacteur doit être authentifié pour soumettre une proposition ? Doit-il déjà avoir un compte sur la plateforme ?

**Comment by davidbgk** [comment]
@cafebabel-webmaster est-ce que `additional info` ne serait pas plus explicite en l'appelant `article` ?

**Comment by davidbgk** [comment]
@cafebabel-webmaster est-ce que tu peux sortir les pièces jointes de l'US ?

**Comment by johangiraud** [comment]
@davidbgk oui oui je les ai sorties voilà.

**Comment by johangiraud** [comment]
@davidbgk non, pas besoin d'être authentifié à cette étape-là. On ne veut fermer aucune porte à ce moment-là.
