### ISSUE TITLE
issue - US6 - Consulter des articles traduits

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#102]
**Page** : article/draft/_id_
**Type** : Fonctionnel
**Contexte** : Après avoir traduit un article dans une langue, si je reviens à l'article parent, le lien de la langue traduite propose une page pour créer la traduction.
**Exemple d'amélioration** : Pourrait proposer le contenu de la traduction en édition.

**Comment by vinyll** [comment]
@pointbar: Est-ce que ca veut dire que ca te repropose ce que tu viens de créer => doublon ?

**Comment by pointbar** [comment]
@vinyll - Ça me repropose de créer une traduction, alors que celle-ci est déjà existante. Pour compléter, si je valide cette nouvelle traduction, j'ai une erreur : "A translation already exists."

**Comment by pointbar** [comment]
Ok now
