### ISSUE TITLE
issue US8 - Recover password

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#104]
**Page** : /reset
**Type** : UX
**Contexte** : Après avoir entré une adresse email (erronée ou valide), en cliquant sur -recover password- alors l'adresse email se superpose visuellement au label - (ff, chrome, safari)

**Comment by johangiraud** [comment]
Oui pour ce problème je ne sais pas @vinyll, la règle c'est _si il y a du contenu dans le champ du `input` alors ajouter la class `active` (qui empêche la superposition)_ Tu sais quel peut être le problème ?

**Comment by johangiraud** [comment]
C'est réglé, il reste juste un bug sur chrome : lorsqu'on demande au navigateur de se rappeler de nous, il ne s'adapte pas au password :
![capture d ecran 2017-12-19 a 15 21 52](https://user-images.githubusercontent.com/32518627/34161267-73e8c47c-e4d0-11e7-96ba-49e965585eb7.png)
On n'avait pas de solution avec @vinyll pour ça.

**Comment by pointbar** [comment]
Oki now
