### ISSUE TITLE
issue - US8 - mail recover password

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#105]
**Page** : /reset
**Type** : Fonctionnel
**Contexte** : En naviguant sur le -preprod.cafebabel.fr- et après avoir entré une adresse email valide et cliqué sur -recover password- alors je reçois un mail avec un lien.
**Problème** : Le lien absolu pointe vers l'adresse : http://127.0.0.1:5000/... alors que je navigue sur http://preprod.cafebabel.fr
**Suggestion d'amélioration** : Le lien pourrait être fabriqué en tenant compte du contexte de navigation.

**Comment by davidbgk** [comment]
We need to [set the appropriated `SERVER_NAME` configuration value](https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L261).

@vinyll can I have an update on how the custom preprod configuration is defined?

**Comment by pointbar** [comment]
Done now
