### ISSUE TITLE
issue - US8 - mail recover password

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#106]
**Page** : /reset
**Type** : UX
**Contexte** : Sur -chrome63- Après avoir entré une adresse mail enregistrée et cliqué sur -recover password- une notification s'affiche -Instructions to reset your password ... -
**Problème** : Au moment de disparaitre, le contour reste fixe et apparent en bas de page.

**Comment by johangiraud** [comment]
N'hésite pas à mettre des screenshot sur le issues @pointbar.
Pour ça je ne vois pas. Je vois un autre problème, c'est que lorsqu'on ne rentre aucun mot de passe, on a l'info-bulle rouge _password not provided_ qui apparaît. Et ensuite quand on clique sur le `input` cette info-bulle ne disparaît pas. C'est autre chose ça ? ou c'est ce dont tu parles ?

**Comment by pointbar** [comment]
@cafebabel-webmaster -Le pb n'est plus reproductible. je close
