### ISSUE TITLE
#US19 - S'inscrire à la newsletter de cafébabel

### ISSUE THREAD

**Issue by cafebabel** [cafebabel/cafebabel.com#11]
ETQ visiteur (contributeurs + lecteurs) je veux pouvoir souscrire à la mailing list pour l'envoi de la newsletter afin d'avoir plus d'info sur cafébabel

- [x] - doit afficher un champs pour inscrire son adresse mail dans le footer
- [x] - doit permettre de valider la selection de l'adresse
- [x] - doit notifier que la souscription a bien été faite

**Comment by pointbar** [comment]
Tiens, surprise, J'l'avais pas prévu dans ce sprint.
Elle est rentrée par où cette US ?  ;) 
@cafebabel-webmaster
