### ISSUE TITLE
issue - US1 - Gérer les articles

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#110]
**Page** : /article/draft/new/
**Contexte** : Je ne suis pas connecté et je demande l'url pour -writing an article-.
**Problème** : L'US #19 indique - doit me renvoyer vers l'authentification/création de profil si je ne suis pas connecté - or le navigateur m'affiche une erreur 403.

**Comment by vinyll** [comment]
Fixed in https://github.com/cafebabel/cafebabel.com/pull/112
