### ISSUE TITLE
Les popups de réseaux sociaux devraient se refermer au clic externe

### ISSUE THREAD

**Issue by vinyll** [cafebabel/cafebabel.com#117]
Sur la page d'édition de mon profil, lorsque je clique sur un logo de réseau, une _tooltip_ s'ouvre avec le champs de saisie.
Lorsque je clique à l'exterieur, il devrait se refermer. Actuellement la _tooltip_ reste ouverte.

**Comment by johangiraud** [comment]
Oui c'est ça, "lorsque je clique à l'extérieur" OU que je clique une nouvelle fois sur l'icône du réseaux qui a le _tooltip_ ouvert
