### ISSUE TITLE
Améliorer la sécurité lors du choix du mot de passe utilisateur

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#119]
#8 doit permettre de valider l'email, mot de passe = minimum 10 caractères, checker qu'il ne soit pas dans la liste des mdp les plus utilisés

**Comment by davidbgk** [comment]
https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/

**Comment by pointbar** [comment]
Duplicates with : #94
