### ISSUE TITLE
Bug doublons affichés dans la liste des contributions dans mon profil

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#125]
se réfère à l'US #13

**Comment by pointbar** [comment]
**URL** : https://preprod.cafebabel.fr/profile
**Contexte** : Affichage de la liste des contributions
**Problème** : Les articles sont affichés en double
**US concernée** : #13

**Comment by davidbgk** [comment]
We (re)iterate over articles within the `_card.html` template.
