### ISSUE TITLE
#US26 - Lister les articles correspondant à un tag

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#126]
ETQ lecteur, je veux consulter les articles pour un tag donné

- [ ] - doit permettre de visualiser la liste des articles pour un tag donné (par ordre antéchrono) : photo de couverture, titres
- [ ] - ne doit renvoyer que les articles dans la langue de l'interface
- [ ] - peut afficher la photo et/ou la description du tag
- [ ] - doit comporter une url partageable de type _/tag/meetmyhood_

**Comment by johangiraud** [comment]
discuter de l'url en fonction des caractères accentués etc.

**Comment by davidbgk** [comment]
Closed in favor of https://github.com/cafebabel/cafebabel.com/pull/152
