### ISSUE TITLE
#US28 - Gérer les 404 et 500

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#131]
ETQ lectrice je souhaite consulter une page d'erreur sympathique pour ne pas perdre ma relation avec CaféBabel quand un truc déconne.

- [x] - doit afficher une page pour les erreurs 404 
- [x] - doit afficher une page générique pour les autres erreurs - (400, 403, 500, ...)
- [x] - doit préserver l'URL de requète
- [ ] - pourrait sauvegarder un contexte simplifié dans un fichier consultable : (url, date, erreur)

**Comment by pointbar** [comment]
@davidbgk @vinyll - j'ai encore des internal server errors - par exemple en essayant de -delete- ma photo de profil et en sauvegardant. 
Les deux liens -back home- me font perdre mon contexte de langue.

**Comment by davidbgk** [comment]
@pointbar est-ce qu'un bug est déclaré pour l'erreur ?

Pour le contexte, malheureusement c'est le mieux que l'on puisse faire pour l'instant…
