### ISSUE TITLE
stack error sur preprod

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#133]
**Contexte** : quand je suis sur le préprod je peux avoir des erreurs sans le détail ex _internal server error_
ou traduction d'un article Bad Request
ValidationError (Article.Translation:None) (Original article in the same language.: ['__all__'])
**Solution** : serait-il possible d'avoir des messages d'erreurs verbeux ciblés pour mieux documenter des issues

**Comment by davidbgk** [comment]
Done in https://github.com/cafebabel/cafebabel.com/pull/264
