### ISSUE TITLE
#US17 - Ajouter une image de profil

### ISSUE THREAD

**Issue by cafebabel** [cafebabel/cafebabel.com#14]
ETQ que contributeur je veux ajouter une image de profil afin de mieux renseigner mon identité.

- [x] - doit permettre d'uploader une image de profil lors de l'édition de mon profil
- [x] - doit permettre de l'uploader via parcourir
- [x] - doit permettre de modifier (changer) et de supprimer la photo.
- [ ] - doit afficher et accepter une taille de fichier maximum (500Ko)
- [ ] - doit afficher la photo dans les contributions de l'auteur/du traducteur (visible à la lecture de l'article)
- [ ] - doit afficher la photo directement à la sélection du fichier (pas besoin de sauver le profil pour la visualiser)

**Comment by vinyll** [comment]
Decision de plannification : faire une prévalidation coté client pour vérifier que le poid soit de moins de 0.5Mo.

**Comment by davidbgk** [comment]
https://github.com/fengyuanchen/cropperjs
