### ISSUE TITLE
Issue - preprod >> Internal Server Error

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#144]
**URL** : https://preprod.cafebabel.fr/register
**Contexte** : Après l'enregistrement d'un article, je ne peux  pas créer de traduction, ni créer des profils.
**Problème** : Pas possible de tester les fonctionnalités dans un contexte de démo. Difficile de proposer à des contributeurs de participer.

**Comment by pointbar** [comment]
Est-ce qu'on pourrait automatiser le deploy en preprod à chaque merge sur master ?

**Comment by vinyll** [comment]
On dirait qu'on a toujours l'erreur @davidbgk:
```
  File "/home/preprod/cafebabel.com/cafebabel/core/mixins.py", line 40, in store_image
    if document is not None and document._upload_image:
AttributeError: 'NoneType' object has no attribute '_upload_image'
```
