### ISSUE TITLE
Espace inopiné à l'affichage de tags

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#151]
**URL**: article/edit
**Problème**: à l'arrivée sur la page, les tags déjà enregistrés prennent un espace à la fin
à partir du moment où on soumet un nouveau tag, le problème est réglé

**Comment by johangiraud** [comment]
Dans le fichier templates/articles/macros.html

**Comment by johangiraud** [comment]
à l'affichage des tags déjà selectionnés : 
![capture d ecran 2018-01-16 a 15 06 59](https://user-images.githubusercontent.com/32518627/34992907-fc70c678-face-11e7-9ca5-c714c7234bbf.png)
ensuite quand on ajoute un tag, tout va mieux ! ;-)
![capture d ecran 2018-01-16 a 15 07 16](https://user-images.githubusercontent.com/32518627/34992908-fc98946e-face-11e7-9094-de3474123709.png)

**Comment by davidbgk** [comment]
See http://jinja.pocoo.org/docs/2.10/templates/#whitespace-control

**Comment by vinyll** [comment]
Why do we need to control whitespaces?
We could trim when saving, and avoid selection in CSS with `user-select: none`

**Comment by johangiraud** [comment]
How do you trim when saving ?

**Comment by vinyll** [comment]
`.strip()` in Python.

**Comment by davidbgk** [comment]
@vinyll it's a bit more complex than that, some spaces are significant in HTML. Open to PR though 😉
