### ISSUE TITLE
<a> intempestifs ajoutés lorsqu'on liste les articles

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#155]
**URL**: partout où est utilisé le block __card.html_
**Problème**: lorsqu'on ajoute la boucle des tag pour afficher la liste de tous les tags d'un article dans la liste d'articles, alors on obtient plusieurs liens au lien d'un seul

**Comment by johangiraud** [comment]
![capture d ecran 2018-01-17 a 17 13 48](https://user-images.githubusercontent.com/32518627/35053322-118b7388-fbaa-11e7-92e6-c63fe0023396.png)

**Comment by davidbgk** [comment]
@cafebabel-webmaster est-ce que l'on peut limiter le lien au titre de l'article (vs. le block complet comme c'était fait jusqu'à présent) ?

**Comment by davidbgk** [comment]
Mmh en fait je ne vois pas trop d'autre option :)

**Comment by davidbgk** [comment]
Fixed in https://github.com/cafebabel/cafebabel.com/pull/152

**Comment by johangiraud** [comment]
oui c'est déjà un trick qui fonctionne. Sinon c'est pas grave, on peut faire un lien sur le titre ET un lien sur l'image. Medium font ça. Tu en penses quoi ? @davidbgk

**Comment by davidbgk** [comment]
J'ai déjà fait le lien sur le titre, je te laisse l'ajouter sur l'image.

**Comment by johangiraud** [comment]
ça marche, merci !

**Comment by johangiraud** [comment]
done.
