### ISSUE TITLE
Langue d'écriture d'un article VS. langue des tags

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#156]
**URL**: article/new
**Problème**: lorsqu'on commence à rédiger un article en français, qu'on ajoute des tags et qu'on reswitch de lange d'écriture : les tags ne changent pas de langue :-(

**Comment by davidbgk** [comment]
See https://github.com/cafebabel/cafebabel.com/pull/140/files#r162084844 I don't get why @pointbar removed that “feature”?

**Comment by pointbar** [comment]
@davidbgk - il reste peut-être à arbitrer ce que l'on fait lorsque l'utilisateur sélectionne une nouvelle langue après avoir ajouté des -tags-

**Comment by davidbgk** [comment]
@pointbar oui c'est un cas assez critique :/ peut-être a minima bloquer la langue lorsque les tags ont été édités ?

**Comment by pointbar** [comment]
@davidbgk ou peut-être après confirmation, supprimer les tags ? - ping @cafebabel-webmaster

**Comment by davidbgk** [comment]
ou peut-être qu'un article en édition ne devrait plus pouvoir changer sa langue en fait ?

**Comment by davidbgk** [comment]
Fixed in 984a33f7de3c1d332196a9208341c1e62d74813e

**Comment by johangiraud** [comment]
@davidbgk @pointbar oui effectivement c'est compliqué comme cas de figure. Moi je voterai plutôt pour supprimer le switch de langue une fois qu'on a commencé à écrire un article. En gros la langue de l'article dépendrait de la langue du site au moment où on a cliqué sur _écrire un article_

**Comment by johangiraud** [comment]
J'ai tranché ça avec les éditeurs ! On aura jamais besoin de créer un article en anglais depuis la version française par exemple. Donc on s'occupe pas de la dépendance des tags et du changement de langue puisqu'... on ne changera plus de langue :-)
Il faut donc supprimer cette fonctionnalité. Vous préférez que j'ouvre une issue ? ou on le fait tout de suite ?

**Comment by davidbgk** [comment]
Il faut ouvrir cette issue et/ou ajouter un test d'acceptance à l'US sur la gestion des langues.

**Comment by pointbar** [comment]
En TA dans #221
