### ISSUE TITLE
Amélioration: 82 - Compléter les méta données

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#158]
**URL** : Toutes les pages exposées
**Problème** : Quelques métas importantes semblent ne pas être prises en compte.
Exemple : 
- charset
- gzip
- meta description
- og:description
- og:title
- og:images
- favicon

**Notes** :
https://socialmetatags.com/?url=https%3A%2F%2Fpreprod.cafebabel.fr%2F&reload=true

**Comment by davidbgk** [comment]
You're testing the 401 returned because we are behind auth…
