### ISSUE TITLE
Issue: 82 - Les urls ne correspondent pas au contexte

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#160]
**URL** : https://preprod.cafebabel.fr/article/draft/5a61b7f5f723b33f535afd03/
**Contexte** : Lorque l'on consulte une page sur préprod et que l'on inspecte les métas.
**Problème** : La racine du site pour les ressources pointe sur : 127.0.0.1:5000
Ex : 
https://preprod.cafebabel.fr/article/draft/5a61b7f5f723b33f535afd03/
http://127.0.0.1:5000/article/draft/5a61b7f5f723b33f535afd03/

**Comment by davidbgk** [comment]
Same issue as https://github.com/cafebabel/cafebabel.com/issues/105
