### ISSUE TITLE
Issue US22 - afficher un changement d'image couverture de page tag

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#163]
**URL**: tag/detail
**Contexte**: lorsqu'on une page tag dispose d'une image, on peut changer cette image via tag/edit.
**Problème**: lorsqu'on valide le changement d'image et qu'on revient sur tag/detail, on voit encore l'image précédente. On voit la nouvelle image uniquement au rechargement de la page en vidant les caches (cmd+shift+R)

**Comment by johangiraud** [comment]
comme #165

**Comment by johangiraud** [comment]
Je n'observe plus le problème en local, à voir en preprod

**Comment by pointbar** [comment]
Je ne constate plus le problème
