### ISSUE TITLE
Amélioration US17 : Ancienne image affichée

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#164]
**URL**. : https://preprod.cafebabel.fr/profile/5a6115bcf723b348966caa0d/
**Contexte** : Lorsque j'insère une photo de profil et que je sauvegarde.
**Problème** : Il faut recharger manuellement la page pour voir la photo.

**Comment by johangiraud** [comment]
Je n'observe plus ce problème en local. À voir quand on déploie sur preprod

**Comment by pointbar** [comment]
Oki now
