### ISSUE TITLE
Issue US22 - markdown pour la description des pages tag

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#171]
**URL**: tag/edit
**Contexte**: je veux créer ou modifier une description évolué pour une page tag

**Comment by pointbar** [comment]
@davidbgk @cafebabel-webmaster - sur preprod le markdown ne semble pas pris en compte 
- https://preprod.cafebabel.com/fr/article/tag/inside-cafebabel/

**Comment by davidbgk** [comment]
@pointbar a `deploy` was missing… better now!

**Comment by pointbar** [comment]
@cafebabel-webmaster - les liens ne sont pas stylés comme sur le reste du site
