### ISSUE TITLE
Conserver l'image de couverture de l'article original lorsqu'on crée une traduction

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#179]
**URL**: translation/new
**Contexte**: à partir d'un article existant, on veut créer une traduction
**Problème**: lors de la création de la traduction, on voudrait conserver, s'il y en a, la photo de couverture originale
**Hint**: {{ image }} & {{ tag }} are not defined in Translations ? @davidbgk @vinyll

**Comment by pointbar** [comment]
Tested
