### ISSUE TITLE
#US35 - Intégrer certains articles

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#181]
ETQ lecteur je veux accéder à certaines archives qui soient intégrées au nouveau fonctionnement (tags, rubriques)

- [ ] - chaque ancien article doit être accessible sous une url de type cafebabel.fr/slug-de-l-article-id
- [ ] - doit afficher un nombre défini d'anciens articles dans le nouveau site
- [ ] - doit afficher l'image de couverture originale, le titre, le chapô, la langue, le contenu texte + image et les légende, l'auteur, le traducteur, leur image de profil et la date originale de publication
- [ ] - doit être lié au profil de son auteur et de son traducteur

**Comment by johangiraud** [comment]
C'est peut-être au final juste un boulot d'éditrice

**Comment by davidbgk** [comment]
Cette US me semble être obsolète maintenant que l'on importe tous les articles ?

**Comment by johangiraud** [comment]
oui tout à fait
