### ISSUE TITLE
#US38 - migrer les profils des contributeurs

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#189]
ETQ contributeur je veux retrouver mon profil sur le nouveau site afin de ne pas devoir en recréer un.

- [ ] - doit importer tous les comptes en conservant : nom, prénom, adresse email, mots de passe
- [x] - peut importer la photo de profil

note : Pour les tags : si on ajoute manuellement un tag à un papier existant, il s'ajoute à la liste de contributions représentées par ce tag

**Comment by pointbar** [comment]
@davidbgk @vinyll @cafebabel-webmaster 
j'ai testé les choses suivantes : 
- vérifier que editors@cafebabel.com était un compte actif sur l'ancienne version 
- constater sur l'ancien site la photo de profil
- vérifier que le compte était actif dans la nouvelle version
- vérifier que la photo de profil était présente
- vérifier que l'on retrouvait le : nom, prénom, l'email et le mot de passe
---
Je n'ai pas pu vérifier que tous les comptes étaient importés.

**Comment by johangiraud** [comment]
J'ai testé avec mon compte perso aussi et ça fonctionne bien. Pareil, je ne peux pas vérifier que TOUS les comptes ont été importés. Comment le voir ?

**Comment by davidbgk** [comment]
Difficile à tester sans avoir la main sur le serveur vu que l'on n'a pas de page listant les comptes.
