### ISSUE TITLE
US#38 Export data from production related to users

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#190]
See https://docs.djangoproject.com/en/2.0/ref/django-admin/#dumpdata

Refs https://github.com/cafebabel/cafebabel.com/issues/189

**Comment by vinyll** [comment]
A dump is available here: `rsync -az prod@91.194.60.65:~/cafebabel/users.json .`

**Comment by johangiraud** [comment]
how should I test this task ?

**Comment by davidbgk** [comment]
@cafebabel-webmaster exceptionally, I'm the tester for that one 😉

**Comment by johangiraud** [comment]
perfect !
