### ISSUE TITLE
US#38 Import first/last name and email from prod users

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#191]
Refs https://github.com/cafebabel/cafebabel.com/issues/189

Dependency https://github.com/cafebabel/cafebabel.com/issues/190

**Comment by davidbgk** [comment]
@cafebabel-webmaster can we have the confirmation of the order between first/last name across considered cultures?

**Comment by johangiraud** [comment]
In English, French, Spanish, Italian, German and Polish the ordre is: first name then last name @davidbgk 👍 Hungarian is the opposite. Since we don't have Hungarian here, I think we're good ;-)
