### ISSUE TITLE
#US3 - Consulter un article

### ISSUE THREAD

**Issue by cafebabel** [cafebabel/cafebabel.com#2]
ETQ lecteur, je peux lire un article pour suivre les sujets de société européen

- [x] - doit posséder une url avec le titre original slugifié
- [x] - doit faciliter le partage
- [x] - doit afficher la langue
- [x] - doit afficher le titre en <title>, le chapeau en `<meta description>`
- [x] - doit afficher la date de publication
- [x] - pourrait afficher le temps de lecture
- [x] - doit afficher l'auteur : son statut d'auteur, son nom/prénom

**Comment by vinyll** [comment]
Reading time is based on 275wpm: https://help.medium.com/hc/en-us/articles/214991667-Read-time
