### ISSUE TITLE
#US5 - Traduire un article

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#20]
ETQ traducteur je veux traduire un article déjà publié afin d'élargir le lectorat

- [x] - doit permettre pour chaque article d'accéder aux traductions à réaliser
- [x] - doit permettre d'accéder via l'interface à une liste des articles filtrés par langue et ne disposant pas d'une traduction : titre, vignette, lien pour créer l'article, lien vers l'article
- [x] - doit permettre la création d'une traduction d'un article publié - (comme #19 )
- [x] - chaque version linguistique peut être traduisible dans une autre langue (pour laquelle il n'y a pas encore de traduction)
- [x] - doit permettre au rédacteur de locker une traduction
- [x] - doit permettre à une éditrice de gérer les traductions lockées (locker/délocker)

**Comment by vinyll** [comment]
_traducteur_ est techniquement le même rôle que _auteur_.
Un auteur a donc la possibilité de traduire à tout moment.

**Comment by davidbgk** [comment]
http://learnmongodbthehardway.com/schema/multilanguage/

**Comment by davidbgk** [comment]
Good to keep in mind: https://docs.mongodb.com/manual/reference/text-search-languages/

**Comment by davidbgk** [comment]
* il y a le même process que pour un article avec draft locké pour une langue puis publication par une éditrice
* par contre un rédacteur peut créer une traduction (différent de la création d'un article)
