### ISSUE TITLE
Issue - liste des auteurs trop longue

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#205]
**URL**: article/create
**Contexte**: on crée un nouvel article et on veut attribuer un auteur dans la liste `<select>`
**Problème**: la liste `<select>` est trop longue et prend super longtemps à être afficher + elle n'est pas très maniable
**Préconisation**:
1_  proposer le profil utilisateur par défaut
2_  abandonner le \<select\> pour un champ avec suggestion

**Comment by davidbgk** [comment]
Proposal: http://leaverou.github.io/awesomplete/#ajax-example

**Comment by davidbgk** [comment]
Might be something to consider: https://www.peterbe.com/plog/how-to-throttle-and-debounce-an-autocomplete-input-in-react
