### ISSUE TITLE
Issue #US38 - Adresse mail non visible dans le profil

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#207]
**URL**: profil/detail
**Contexte**: je suis éditrice et je veux trouver l'email d'un contributeur en allant sur son profil
**Problème**: lorsque je vois le _full name_, je ne peux plus voir l'adresse mail du contributeur
**Solution**: ajouter un champs pour l'adresse mail visible uniquement par les éditrices et par le contributeur lui-même

**Comment by pointbar** [comment]
Peut-être que l'adresse mail pourrait-être visible en étant connecté peu importe le rôle ?

**Comment by johangiraud** [comment]
Pas terrible niveau intimité et protection des données quand même. Ton adresse mail est visible par tout le monde comme ça ? bof, non ?

**Comment by pointbar** [comment]
Pas par tout le monde, par les contribut·eur·rice·s.
En laissant le choix ce serait mieux.

**Comment by johangiraud** [comment]
oui. enfin je ne vois pas pourquoi un contributeur A voudrait avoir le mail d'un contributeur B. Mais ça protège déjà un peu oui s'il faut avoir un compte pour pouvoir voir cette adresse
