### ISSUE TITLE
Issue : message d'erreur non-explicites sur preprod

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#208]
**Context** : Les messages d'erreurs sur pré-prod renvoient une erreur 500 générique : 
> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server > is overloaded or there is an error in the application.
**Problème** : 
Cela ne permet pas de qualifier une issue, et oblige le testeur à refaire le test en local.

**Comment by davidbgk** [comment]
Done via https://github.com/cafebabel/cafebabel.com/pull/264
