### ISSUE TITLE
Issue : Emails des auteurs en création d'article

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#209]
**URL** : édition ou création d'articles
**Contexte** : Lorsque j'essaye de sélectionner mon email, le menu <select> charge l'ensemble des contributeurs.
**Problème** : Cette liste est trop longue à charger et à utiliser

**Comment by davidbgk** [comment]
Duplicate of https://github.com/cafebabel/cafebabel.com/issues/205
