### ISSUE TITLE
#US6 - Consulter des articles traduits

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#21]
ETQ lecteur à la consultation de l'article je peux accéder aux traductions afin de le lire dans la langue que je préfère

- [x] - doit afficher les langues disponibles pour l'article
- [x] - doit indiquer la langue original de l'article
- [x] - doit afficher la traductrice : son statut de traductrice, son nom/prénom, team

**Comment by vinyll** [comment]
Pas besoin de conserver la langue d'origine de traduction. Un article en anglais, traduit de l'espagnol vers le portugais, le fait que ce soit fait depuis l'espagnol n'a pas d'importance.
