### ISSUE TITLE
US#36 Fix paths of images within imported articles

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#218]
* On preprod we have https://preprod.cafebabel.fr/article/12-years-a-slave-the-black-experience-today-5a7b6ee9f723b31d36aaa659/ with an image toward https://m.cbabel.eu/cache/34/93/3493bece2eaeef93c200884edfe30004.jpg 
* In production we have http://www.cafebabel.co.uk/culture/article/12-years-a-slave-the-black-experience-today.html with that same image being http://m.cafebabel.com/cache/9a/0a/9a0a6c3262b5cdd49aeee062a9a1b5dd.jpg

The exported body contains the string `http://m.cbabel.eu/cache/34/93/3493bece2eaeef93c200884edfe30004.jpg` within `articles40000-70000.json` (without the httpS)

**Comment by vinyll** [comment]
FYI the cache folder is in `/home/prod/cafebabel/data/medias/cache/`.

Therefore `http://m.cafebabel.com/cache/9a/0a/9a0a6c3262b5cdd49aeee062a9a1b5dd.jpg` points to `/home/prod/cafebabel/data/medias/cache/9a/0a/9a0a6c3262b5cdd49aeee062a9a1b5dd.jpg`
