### ISSUE TITLE
Les boutons de partage sur les réseaux sociaux sont factices

### ISSUE THREAD

**Issue by vinyll** [cafebabel/cafebabel.com#231]
Losque je souhaite partager un article ou une page de tag, les bouton en haut à droite en lien avec les réseaux sociaux ne se cliquent pas vraiment.
Aucune action ne se passe alors que je souhaiterais être redirigé vers le réseau social.

**Comment by johangiraud** [comment]
Les bouton en haut à droite ne sont pas des boutons de partage. Ce sont des liens vers les réseaux sociaux de cafébabel. Les liens sont des _#_ parce qu'ils doivent être dynamiques. (en fonction de la langue, il y a par exemple une page facebook française et une page facebook anglaise). Comme les différentes versions linguistiques ne sont pas implémentées, pas possible d'avoir des liens dynamiques pour le moment.

**Comment by vinyll** [comment]
C'est un peu dommage d'avoir des boutons factices.
Une possibilité aurait été de mettre les vrais liens vers les références en anglais (puisque c'est la langue actuelle de l'interface), qui sera enrichi avec la venue des autres langues.

**Comment by johangiraud** [comment]
ok je fais ça.
