### ISSUE TITLE
Issue - variable 'const' sur safari

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#234]
**URL**: partout
**Contexte**: je veux accéder au site de cafébabel sur safari 10.1.2 (10603.3.8)
**Problème**: le préloader ne s'efface jamais car la variable `const` n'est pas correctement interprétée par safari

```
SyntaxError: Can't create duplicate variable that shadows a global property: 'preloader'
```
https://stackoverflow.com/questions/29194024/cant-use-let-keyword-in-safari-javascript
https://stackoverflow.com/questions/40091136/cant-create-duplicate-variable-that-shadows-a-global-property

**Comment by vinyll** [comment]
Le 1e lien que tu mentionnes concerne Safari 8 qui est obsolète. C'est pareil avec les autres anciens navigateurs.
Le 2nd lien, j'y [avais répondu l'année dernière sur la même page](https://stackoverflow.com/a/42210709/328117).

En bref, sur Safari tu ne peux pas avoir `const nomDElement` et un  `id=nomDElelement` qui ont la même valeur. C'est un bug qui traine chez eux.
Donc tu peux par exemple:
- soit utiliser `var preloader - …` avec un commentaire,
- soit renommer l'id ou le nom de variable Ex: `id=preloaderLayer` et `const preloader = document.querySelector('#preloaderLayer')`

**Comment by johangiraud** [comment]
Ha c'est fou ça, tu es partout ! 😉 (Tiens c'est dingue, ton commentaire sur stack a exactement 1 an aujourd'hui 🎂 )
D'accord, étrange comme spécificité. Et ça marche aussi avec le nom de la `class` et celui de la `const` ? Il faut qu'ils soient différents ?
En tout cas j'ai changé le nom de l'id, c'est le plus cohérent à mon sens. (https://github.com/cafebabel/cafebabel.com/pull/220/commits/dd2b38ffad08837c530ecde03b91ec34798a43c4)
Merci

**Comment by vinyll** [comment]
C'est uniquement avec un `id` que ca fait ça, pas les `class` ni la balise.
Étonnant que ca n'ait toujours pas été corrigé…

**Comment by johangiraud** [comment]
Comme je disais, j'ai safari 10. Ça a dû être corrigé sur la version 11 j'imagine
