### ISSUE TITLE
502 sur la page To-translate

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#235]
**URL**: https://preprod.cafebabel.com/en/article/to-translate/ par exemple
**Contexte**: je veux accéder aux articles à traduire
**Problème**: j'obtiens une erreur 502 sur cette page

![capture d ecran 2018-02-13 a 13 02 45](https://user-images.githubusercontent.com/32518627/36148987-38e605e6-10be-11e8-83fe-574d93c44791.png)

**Comment by pointbar** [comment]
duplicate with #262
