### ISSUE TITLE
Browsers support?

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#24]
To be discussed during the next meeting.

**Comment by cafebabel** [comment]
Support navigateurs récents uniquement pour le desktop. Pour les mobiles : à discuter, je pense qu'on doit descendre jusqu'à iOS 7. À voir

**Comment by cafebabel** [comment]
- Chrome : 50%
![chrome 50](https://user-images.githubusercontent.com/7603230/31129003-ab678ec4-a853-11e7-811d-7471826fb195.png)
- Safari : 25%
![safari 25](https://user-images.githubusercontent.com/7603230/31129015-b115dd58-a853-11e7-84b3-ef3e40bf7991.png)
- Mozilla : 9%
![mozilla 9](https://user-images.githubusercontent.com/7603230/31129014-b1030142-a853-11e7-9a01-b98a37e69850.png)
- Samsung Internet : 4%
![samsung internet 4](https://user-images.githubusercontent.com/7603230/31129012-b0fd9694-a853-11e7-8590-d4482af82bc4.png)
- IE : 3%
![ie 3](https://user-images.githubusercontent.com/7603230/31129532-22ba94c0-a855-11e7-9947-a6e21d13c69c.png)
- Edge : 2%
![edge 2](https://user-images.githubusercontent.com/7603230/31129011-b0cda682-a853-11e7-9e63-a2aeeea80dc5.png)

**Comment by vinyll** [comment]
https://github.com/scopyleft/backlog/blob/master/DoD.md#supports-navigateurs

**Comment by pointbar** [comment]
Présent dans le DoD
