### ISSUE TITLE
Wrong authors for imported articles

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#249]
Sometimes, we attribute the wrong author to a given article (translation?) when importing old data. It has to be discussed with editors to find pathologic cases.

**Comment by vinyll** [comment]
The article https://preprod.cafebabel.com/de/article/salsa-y-comida-racista-pero-que-tonterias-son-estas-5a7b71ddf723b31d36aae47b/ is assigned to Katha. She is the author of the original article but not for the translations.
Same case [here](https://preprod.cafebabel.com/de/article/marsiglia-e-larte-di-strada-in-europa-5a7b71d2f723b31d36aae3c0/), she's the author of the original but not of the italian translation.

Katha is not the author of https://preprod.cafebabel.com/de/article/ein-nachruf-verbotene-liebe-wird-abgesetzt-5a7b6e22f723b31d36aa9152/. It should be assigned to Julia Korbik.
Note that [the original article](http://www.cafebabel.de/lifestyle/artikel/ein-nachruf-verbotene-liebe-wird-abgesetzt.html) was correctly assigned to Julia.

**Comment by kathakloss** [comment]
@pointbar It seems that the problem of wrong authorship is repared (at least in my profile) The article by Julia Korbik is not there anymore.

But the problem of translations remains, the translations of my 'Original version' articles should not be shown in my own profile but in the profile of the respective translators. An example https://preprod.cafebabel.com/it/article/un-assaggio-di-germania-nel-cuore-di-parigi-udo-wunderbar-kiez-5aa051d3f723b363fc60b309/ I'm the author of the original German version (which doesn't show in my profile), the Italian translation should be taken off and added to the profile of Italian translator Ilaria Cubalchini

**Comment by larabullens** [comment]
So all of my articles are there (as well as *all* of their translations), but when I scroll all the way down I can't see my entire list. I have a total of 28 articles that I've published on Cafébabel, and I can only scroll until the one called: _"Dutch YouTubers get high with government money"_

**Comment by vinyll** [comment]
Hey @larabullens!
The current number of displayed articles is limited to the 25 latest for performance purpose.
Can you confirm that _"Dutch YouTubers get high with government money"_ is actually your 25th?

**Comment by larabullens** [comment]
@vinyll No, it's the 5th most recent. All of the 'other' articles in my contributions are just the translations of the articles. Here is are two screenshots to explain: 
![screen shot 2018-03-14 at 16 55 10](https://user-images.githubusercontent.com/37072151/37414004-7fbbeb2e-27a8-11e8-9906-4c1725c18cbe.png)
![screen shot 2018-03-14 at 16 54 41](https://user-images.githubusercontent.com/37072151/37414005-7fdb96f4-27a8-11e8-8a10-7ee20d849857.png)
