### ISSUE TITLE
Deal with images and optimization

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#256]
A follow-up on https://github.com/cafebabel/cafebabel.com/pull/255

We need to be able to resize and optimize content submitted by authors/editors, maybe using https://flask-resize.readthedocs.io/index.html

For the record, it has already been made for old articles so it's mainly for old users and old main pic of articles + all recent ones (do not forget tags).

**Comment by vinyll** [comment]
Maybe can we use the [Mongoengine ImageField](http://docs.mongoengine.org/apireference.html#mongoengine.fields.ImageField) `size` and `thumbnail_size` for main images?
It won't solve the article content image size though.

**Comment by pointbar** [comment]
@davidbgk toujours bizarre (je trouve) le fait que les sites de tests n'affichent que le moulin à café.
C'est le cas pour les pages :
- home
- tag
- article
Et même login (https://cafebabel.com/fr/login)

**Comment by pointbar** [comment]
Sinon l'optimisation des images est ok

**Comment by davidbgk** [comment]
@pointbar quels sites de test ? Sur https://www.webpagetest.org/result/180412_3B_cee340aae4fe9ec6cfe398c80be9095c/ on voit bien la page qui s'affiche.

**Comment by pointbar** [comment]
@davidbgk : je ne peux pas tester pour l'instant webpagetest semble semi-hs, l'écran affiche un : "restart to to finish updating your pc"
Et je teste sur : https://developers.google.com/speed/pagespeed/insights/
