### ISSUE TITLE
archives : iframes invisibles

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#259]
**URL**: single article par exemple https://preprod.cafebabel.com/fr/article/translation/5a95e061f723b3339b09a7b4/
**Contexte**: je veux lire une vidéo embed dans l'article
**Problème**: la vidéo ne s'affiche pas.
**Hint**: lorsque je change manuellement via l'inspecteur la `src` de `http://www.youtube...` à `//www.youtube...`, la vidéo s'affiche. Lorsque je re-change pour `http://www.youtube...` la vidéo reste visible :
![capture d ecran 2018-02-28 a 12 19 00](https://user-images.githubusercontent.com/32518627/36785143-2f382d24-1c82-11e8-88e9-d8eec620427b.png)

![capture d ecran 2018-02-28 a 12 19 20](https://user-images.githubusercontent.com/32518627/36785148-315f6eaa-1c82-11e8-8873-cc41134529f6.png)

**Comment by johangiraud** [comment]
#335

**Comment by johangiraud** [comment]
le problème persiste : https://preprod.cafebabel.com/en/article/video-europe-takes-baby-steps-to-reduce-gender-pay-gap-5aaa9695f723b3054291b7d8/
Peut-être est-ce dû à l'adresse de youtube qui n'est pas sécurisé ? Par exemple ici c'est : 
```
<iframe class="youtube-player" frameborder="0" src="http://www.youtube.com/embed/XcO2tWiNNqU" title="Video player" type="text/html"></iframe>
```

**Comment by davidbgk** [comment]
There are:

* 116 articles with Vimeo iframes, all have an `https` embeds.
* 12050 articles with Youtube iframes and `http` embeds.
* 5 articles with Youtube iframes and `https` embeds.
* 2 articles with Google Spreadsheets and `https` embeds
* 19 articles with Google Docs and `https` embeds

Alright, I need a script :)

**Comment by davidbgk** [comment]
Stuck because we need to import new data to be able to test it in (pre)prod

**Comment by pointbar** [comment]
@davidbgk - je viens de revérifier :
https://cafebabel.com/en/article/meet-my-hood-zuglo-budapest-5aa9b697f723b31298c0c6a8/
ne permet pas de consulter la vidéo : youtube
```
Mixed Content: The page at 'https://cafebabel.com/en/article/meet-my-hood-zuglo-budapest-5aa9b697f723b31298c0c6a8/' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/_l2WGu6YJ2U'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by pointbar** [comment]
@cafebabel-webmaster @davidbgk 
Est-ce possible d'avoir des urls d'articles contenant des iframes :

**Comment by davidbgk** [comment]
@pointbar il manquait un déploiement on dirait, c'est en cours de réimport…

**Comment by pointbar** [comment]
@davidbgk oui ça marche
