### ISSUE TITLE
Lien -to translate- en internal server error

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#262]
URL : https://preprod.cafebabel.com/fr/article/to-translate/
Contexte : à partir de la home, si je clique sur le lien -to-translate-
Problème : -Internal server error-

**Comment by davidbgk** [comment]
This is because we lack pagination here too, so mongo is out of memory.

Probable same as https://github.com/cafebabel/cafebabel.com/issues/235

**Comment by vinyll** [comment]
I would suggest to limit the maximum number of articles that are displayed while we don't have pagination.
