### ISSUE TITLE
Informations du contexte par défaut

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#263]
Pages : édition d'un nouvel article
Contexte : Lorsque j'édite un article en français. Le champs langue est positionné sur EN par défaut et sur le premier utilisateur dans la liste -author-
Problème : Il faut repositionner les options par défaut pour être synchroniser avec mon contexte.

**Comment by vinyll** [comment]
Peut-être que cette tâche aurait sa place avec la mise en place des langues
