### ISSUE TITLE
Size of article cover pic

### ISSUE THREAD

**Issue by kathakloss** [cafebabel/cafebabel.com#278]
page: /article

Quand je tente d'uploader l'image principale pour un article, rien ne se passe. Donc j'imagine qu'elle était trop lourde. Mais je n'ai pas de message d'erreur.

D'ailleurs, si c'est vraiment ça = chiant = car il faut resize puis réuploader = perte de temps assez considérable

**Comment by pointbar** [comment]
Est-ce que tu peux transmettre l'image que tu as essayé de placer ? - @kathakloss 
(attach files by dragging & dropping, ...)

**Comment by pointbar** [comment]
Duplicate with #281
