### ISSUE TITLE
Taille de la vidéo dans un article

### ISSUE THREAD

**Issue by AliceCases** [cafebabel/cafebabel.com#283]
Dans l'article "Meet My Hood : Le Quartier Latin, à Paris", la vidéo apparaît en tout petit. Je pense que ça serait mieux qu'elle apparaisse en plus gros, parce que la taille actuelle ne permet pas un visionnage correct. En plus ce n'est pas en cohérence avec la taille des images du même article.

**Comment by johangiraud** [comment]
duplicate with #259
