### ISSUE TITLE
US #38 - changing language on a category displays the equivalent category

### ISSUE THREAD

**Issue by vinyll** [cafebabel/cafebabel.com#297]
when browsing on `/en/tag/impact/` and changing to fr, I should be directed to `/fr/tag/impact/`.
Same for the other 3 categories.

#290

**Comment by pointbar** [comment]
Pour info, si la rubrique n'est pas renseignée dans une langue, on obtient une 404 - en demandant le changement de langue.
Ça me va, car je pense que ça ne devrait pas se produire dans la pratique d'avoir une rubrique orpheline.
