### ISSUE TITLE
#US22 - Administrer une page tag

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#30]
ETQ éditrice je veux gérer une page tag afin que les visiteurs puissent consulter les articles par thèmes

- [ ] - doit permettre d'ajouter une image et/ou une description (markdown) pour personnaliser une page tag
- [ ] - doit permettre de modifier un tag

**Comment by davidbgk** [comment]
@cafebabel-webmaster en cas de modification d'un tag, est-ce que le slug change également ? Si oui est-ce qu'il faut gérer les redirections associées ? (404, SEO, etc) À discuter en prochaine daily.

**Comment by davidbgk** [comment]
Closed in favor of https://github.com/cafebabel/cafebabel.com/pull/153

**Comment by johangiraud** [comment]
@davidbgk on n'aura pas à modifier un tag. Il n'y a aucune situation où on doit modifier un tag après un certain temps. À part dans le cas d'une erreur de frappe et d'inattention et on devra juste supprimer le tag et le recréer : beaucoup plus simple comme ça !

**Comment by vinyll** [comment]
On ne modifiera jamais non plus l'image ni le chapo ?

**Comment by johangiraud** [comment]
Si ! L'image et la description doivent pouvoir changer. Par exemple pour MeetMyHood, on veut pouvoir updater l'image peut-être quand il y a nouvel article qui sort en lien avec un événement d'actualité ou quelque chose dans le genre
