### ISSUE TITLE
contenu sponsorisé

### ISSUE THREAD

**Issue by ffameli** [cafebabel/cafebabel.com#303]
Du contenu sponsorisé en adéquation avec la ligne éditoriale pourra apparaitre
Comment prévenir le lecteur que cet article n'est pas de nous ? 
Il s'agit d'une obligation légale

**Comment by pointbar** [comment]
@ffameli - Possible de l'ajouter dans l'article ou avec un tag par exemple ?

**Comment by ffameli** [comment]
oui bonne idée
