### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#339]
*Page* : Error
*Contexte* : Lorsque les erreurs proviennent du serveur elle ne sont pas capturées. Par exemple en essayant de -delete- ma photo de profil et en sauvegardant. #318
*Problème* : L'utilisateur reçoit une erreur système.

**Comment by johangiraud** [comment]
Lorsqu'on essaie de supprimer la photo de couverture d'un article aussi

**Comment by vinyll** [comment]
Resolution: link the current Flask error 500 template to Nginx

**Comment by pointbar** [comment]
@vinyll @davidbgk 
J'ai essayé de générer une situation de plantage.

Si je demande une traduction :
> https://preprod.cafebabel.com/fr/article/translation/new/?original=5acb7971f723b36cf8f17848
Puis que je change la langue dans l'url :
> https://preprod.cafebabel.com/en/article/translation/new/?original=5acb7971f723b36cf8f17848

À la sauvegarde, J'obtiens une erreur qui n'est pas capturée :
Bad Request
This article already exists in this language.
