### ISSUE TITLE
Changement de catégories adapté au changement de langue

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#342]
**Page** : Page tag pointant sur une catégorie
**Contexte** : Lorsque je consulte la page d'une catégorie et que je change de langue, je suis redirigé vers la home de la langue.
**Préconisation** : je souhaiterais être redirigé vers la catégorie dans la nouvelle langue sélectionnée

**Comment by davidbgk** [comment]
Duplicate of https://github.com/cafebabel/cafebabel.com/issues/297

Sorry, my bad.
