### ISSUE TITLE
entrées menu déroulant 

### ISSUE THREAD

**Issue by ffameli** [cafebabel/cafebabel.com#343]
Entrées manquantes à développer : 
Network (page évolutive)
Nos prestations (page quasi statique)

Entrées potentielles : 
Vidéos/Podcasts (sur la même ligne)

**Comment by pointbar** [comment]
@ffameli un peu cryptique ;) et il me semble qu'il y a plusieurs Issues dans cette issue ?

**Comment by ffameli** [comment]
ok je crée de nouvelles issues

**Comment by pointbar** [comment]
merci mec ;)
