### ISSUE TITLE
Consulter les drafts par la langue sélectionnée

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#348]
**Page** : view Drafts
**Contexte** : je consulte les drafts avec une langue sélectionnée.
**Préconisation** : je souhaiterais que ne soit affiché que les drafts de la langue sélectionnée

**Comment by davidbgk** [comment]
Make sure drafts newly created appear within that list.

**Comment by pointbar** [comment]
Une article créé en -draft- n'apparait pas dans la liste des drafts :
ex: https://preprod.cafebabel.com/fr/article/draft/5aa9ba60f723b3379f34856b
#330

**Comment by pointbar** [comment]
Je ne sais pas trop quoi faire quand une US à tester comporte des erreurs.
- Est-ce que je la ré-ouvre ?
- Est-ce que je la marque comme testée et j'ouvre une issue ?

Dans un contexte -scrum- elle resterait ouverte et commentée.

**Comment by pointbar** [comment]
@davidbgk - ces cartes qui, comme des saumons, remontent le flux me grattent.

**Comment by davidbgk** [comment]
@pointbar je sais, ouvert à mieux :(

**Comment by pointbar** [comment]
@davidbgk - Proposition : ⚗️
1- laisser la carte en <bloquée> quand elle n'est pas démontrable et ouvrir une issue qui démarre au début du flux. Et peut-être compléter en ajoutant une mention de l'issue couplée au déblocage dans la carte.
2- laisser la carte continuer le flux quand elle reste démontrable et ouvrir une issue qui démarre au début du flux.

/me Peut-être un peu maladroit de lancer le sujet la veille de la démo.
