### ISSUE TITLE
Add tag #Raw for a new draft

### ISSUE THREAD

**Issue by kathakloss** [cafebabel/cafebabel.com#364]
Page: /article

Problème: Quand j'essaye d'ajouter un tag et clique sur + par la suite, rien ne se passe/ voire il disparaît https://preprod.cafebabel.com/de/article/draft/5aa94ba4f723b33760fdd734

**Comment by pointbar** [comment]
Je crois que ça vient du fait que le tag présent sur cette page commence par un caractère spécial  -#- -#bosnie-

**Comment by kathakloss** [comment]
@pointbar oui, en supprimant #Bosnie, le système a pris en compte Raw. C'est bon!
