### ISSUE TITLE
Hyperlink in article covers text

### ISSUE THREAD

**Issue by thom4parisot** [cafebabel/cafebabel.com#367]
<img width="1432" alt="screen shot 2018-03-14 at 23 04 28" src="https://user-images.githubusercontent.com/138627/37435754-8c065840-27dc-11e8-95bf-7384eb2046e7.png">

As seen on https://preprod.cafebabel.com/en/article/how-to-target-the-right-clients-for-you-5aa05204f723b363fc60b649/ with Firefox 59 on macOS

**Comment by johangiraud** [comment]
I can't see the pb with firefox 59.0 (quantum) on macOS. Anyway, I dont see how a `background-color` can hide text.

**Comment by thom4parisot** [comment]
Yeah it's weird. It's okay on https://preprod.cafebabel.com/en/article/cafebabel-is-hiring-a-new-editorial-coordinator-5aa164c3f723b363d509a76b/

![image](https://user-images.githubusercontent.com/138627/37454712-335b91a4-2833-11e8-8857-10d0d96bf97c.png)

**Comment by thom4parisot** [comment]
So I suspect it's linked to the length of the text. And more importantly, when it **spans on two lines** or more.

----

OK

<img width="1088" alt="screen shot 2018-03-15 at 09 32 03" src="https://user-images.githubusercontent.com/138627/37454921-be12928e-2833-11e8-84e6-ebbcfdb79e48.png">



----

NOT OK

<img width="1093" alt="screen shot 2018-03-15 at 09 30 53" src="https://user-images.githubusercontent.com/138627/37454870-966c6048-2833-11e8-82d8-d3f133f2eea7.png">

**Comment by johangiraud** [comment]
I have the problem too. Indeed it seem to occur only for more than 1 line links.

**Comment by cafebabel-webmaster** [comment]
fixed #371
