### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by vinyll** [cafebabel/cafebabel.com#374]
Fix #372

**Comment by pointbar** [comment]
@davidbgk @vinyll @cafebabel-webmaster - j'ai l'impression qu'il n'y a pas assez d'informations pour pouvoir tester ?

**Comment by johangiraud** [comment]
Right @pointbar, we can only observe that some words have been changed to fit better both english language and Cafébabel values. Don't know how to go further than this...

**Comment by pointbar** [comment]
@cafebabel-webmaster - je me déclare incompétent, je vais essayer de voir avec Lara
