### ISSUE TITLE
Page Network

### ISSUE THREAD

**Issue by davidbgk** [cafebabel/cafebabel.com#395]
- Discriminer la page tag network pour pouvoir la styler autrement

**Comment by vinyll** [comment]
On pourrait mettre le tag dans la _class_ du _body_ : `{% block body_class %}tag-{{ tag }}{% endblock %}` pour que Maitre Johan puisse jouer avec ?

**Comment by johangiraud** [comment]
ha tu lis dans mes pensés @vinyll, je suis en train de le faire

**Comment by johangiraud** [comment]
https://github.com/cafebabel/cafebabel.com/pull/397

**Comment by johangiraud** [comment]
Vous pensez que ça serait plus propre de créer une macro pour pouvoir ajouter dynamiquement une feuille de style qui s'appellerait genre `styles-page-network.css` ?
Ah mais j'ai un doute pour le "dynamiquement", pour toutes les autres page tag, il n'y aura pas forcément de feuille de style correspondante :/

**Comment by vinyll** [comment]
J'imagine que tu peux juste mettre ces styles dans la CSS où sont les styles des _tags_

**Comment by vinyll** [comment]
@cafebabel-webmaster c'est en cours du coup?

**Comment by johangiraud** [comment]
oui je vais faire une nouvelle PR
