### ISSUE TITLE
Le markdown helper n'est pas suffisamment accessible

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#407]
**URL**: article/edit
**Contexte**: je veux mettre en forme un article en langage markdown
**Problème**: le markdown helper est situé en-dessous du textarea, c'est trop loin et pénible de devoir faire des allers/retours pour voir comme formatter le contenu

**Comment by pointbar** [comment]
La croix de fermeture ne fonctionne pas. @cafebabel-webmaster

**Comment by johangiraud** [comment]
Elle fonctionne. C'est juste que si tu re-scroll, le markdown-helper repasse en position fixed. Tu penses que ça serait mieux d'enlever la position fixed "pour toujours" ?

**Comment by pointbar** [comment]
Sur pre-prod et FF60 lorsque je survole la croix mon curseur reste en -flèche- si je clique rien ne se passe.

**Comment by johangiraud** [comment]
Ok je vais regarder
