### ISSUE TITLE
Menu principal

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#408]
Éléments du menu principal :

_Non connecté :_
- Login
- Sections (comment les afficher dans l'ordre alphabétique cette fois?)
- Network
- About

_Connecté en tant que contributeur :_
- Profile/Log out
- Sections
- Network
- About
- Pitch an article (seulement sur les petits écrans)
- Translate an article (seulement sur les petits écrans)

_Connecté en tant qu'éditrice :_
- Profile/Log out
- Sections
- Network
- About
- Translate an article (seulement sur les petits écrans)
- New article
- Pending drafts

**Comment by pointbar** [comment]
@cafebabel-webmaster 

**Non connecté** 
- j'ai *pitch pour participate* qui ne semble arrivé que pour les contribut·eurs·rices
**Pour tous**
- - quand je change de langue je perds les -sections-

**Comment by johangiraud** [comment]
- _Pitch an article_ doit être dans le menu lorsqu'on n'est pas connecté ET lorsqu'on est connecté. (Sur desktop, il apparait comme un bouton, pas dans le menu)
- S'il n'y a aucun article tagué avec le nom d'une catégorie, cette catégorie n'existe pas. Je pense qu'on est dans cette situation pour certaines langues actuellement sur preprod.
