### ISSUE TITLE
Gérer le cache des fichiers statiques

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#409]
Celui-ci devrait être remis à zéro côté navigateur lors de la modification d'un fichier CSS/JS.

**Comment by davidbgk** [comment]
https://flask-assets.readthedocs.io/en/latest/ might be integrated to deal with that issue.

**Comment by pointbar** [comment]
@davidbgk @cafebabel-webmaster @vinyll 

Je constate les avantages du cache au rechargement :
- 36 requêtes - 4,60 Mo / 4,56 Mo transférés- Terminé en : 15,33 s - load: 15,37 s
- 31 requêtes - 4,52 Mo / 4,47 Mo transférés - Terminé en : 6,30 s - load: 6,35 s

J'y vois moins clair en grattant :
Sur : https://www.webpagetest.org/result/180412_1D_5eb57d01ee9a31b071db629e692bcca8
II y a toujours que le moulin à café en simulant l'exploration de la page
Et les performances semblent médiocres en cache et compression

Sur Page Test G00gle => moulin à café en simulant l'exploration de la page :
> https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fwww.cafebabel.com%2F&tab=desktop
Je ne sais pas à quel point c'est embêtant.

Avec curl, je récupère une 301.
Et les moteurs semblent indéxer cette 301 : 
![capture d ecran 2018-04-12 a 12 03 29](https://user-images.githubusercontent.com/451908/38670716-dfa25c00-3e49-11e8-8289-9257f56738e1.png)

Je pousserais bien avec la console, il faudrait un fichier à la racine pendant quelques minutes.
```
$ echo google-site-verification: google80aebbf4871913f2.html > google80aebbf4871913f2.html
```

**Comment by davidbgk** [comment]
@pointbar les images ne sont pas encore optimisées, c'est là où réside la plus grosse optimisation.
