### ISSUE TITLE
Poser un google analytics sur -www.cafebabel.com-

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#423]
ETQ Matt je veux consulter le traffic pour vérifier l'audience et éclairer les décisions de CFB

- [x] doit permettre de moucharder l'ensemble des pages non privatives
- [x] doit permettre de moucharder l'ensemble des pages privatives

note : valider le site par google (fichier à poser à la racine) permettrait d'utiliser : https://search.google.com

**Comment by davidbgk** [comment]
https://www.innocraft.cloud/ ?

**Comment by vinyll** [comment]
Innocraft might turn expensive based on the # of page-views on Cafebabel
