### ISSUE TITLE
Upload des images impossible

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#426]
**URL**: partout où on peut uploader des images
Les images ne peuvent pas être importées.
![capture d ecran 2018-04-11 a 10 46 36](https://user-images.githubusercontent.com/32518627/38618551-4742ffdc-3d9a-11e8-9412-52ef2bea0e1f.png)

**Comment by vinyll** [comment]
Sorry about that. The Nginx root property was not pointing to the correct path.
fixed
