### ISSUE TITLE
Preview des images ne fonctionne plus

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#428]
**Page** : /Profil/edit
**Contexte** : Lorsque je sélectionne une photo de profil la pré-visualisation avant sauvegarde ne s'affiche pas correctement.
![capture d ecran 2018-04-12 a 11 43 57](https://user-images.githubusercontent.com/451908/38669522-e2e90588-3e46-11e8-8510-2583157914d5.png)

**Comment by johangiraud** [comment]
fixed.
