### ISSUE TITLE
Images de couverture d'une page tag resizées

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#434]
je ne veux pas que les images de couverture d'un tag soit resizées si petites. Elles doivent être 2000x1333px

![capture d ecran 2018-04-13 a 10 36 26](https://user-images.githubusercontent.com/32518627/38725237-fb93d7dc-3f06-11e8-8bda-df2cecf3292d.png)

**Comment by davidbgk** [comment]
You need to configure a new size in config and then use it here: https://github.com/cafebabel/cafebabel.com/blob/master/cafebabel/templates/articles/tags/detail.html#L41

**Comment by johangiraud** [comment]
I don't think it's here, cause this image is actually a `background-image` of the div `.tag-header`
![capture d ecran 2018-04-13 a 17 13 54](https://user-images.githubusercontent.com/32518627/38742940-189e2cba-3f3e-11e8-90ca-f1f34b2debeb.png)
