### ISSUE TITLE
Permettre à un éditeur de modifier le traducteur 

### ISSUE THREAD

**Issue by kathakloss** [cafebabel/cafebabel.com#442]
Quand je crée une traduction à la place d'un traducteur, pouvoir l'ajouter en tant que traducteur.

**Comment by matthieuamare** [comment]
Scénario probable : une traductrice souhaite traduire un texte et fait la demande à un éditeur de la lui réserver pour plus tard. Il faudrait que l'éditeur puisse ajouter ladite traductrice à la traduction (comme c'est le cas pour un article) pour la lui assigner.

**Comment by ffameli** [comment]
idée : avoir la même fonctionnalité qu'avec les auteurs, pouvoir choisir le traducteur arbitrairement par l'éditeur. fréquemment utilisé par les éditeurs.
plus important pour les éditeurs. ex : publication simultanée de 5 articles au même moment, je n'ai aps accès à la vo sur le site pour faire la trad en tant que traducteur. 
matelas de sécurité pour les éditeurs pour publier à la place d'un traducteur. 



**n'est pas une priorité,** il faudra changer nos habitudes en créant des drafts traduisibles. 

--> nouvelle pratique : l'éditeur créée un draft / il envoie l'url au traducteur / le traducteur se log et enregistre la trad / l'éditeur publie la trad
--> inconvénient : création d'url repérable par google qui altèrent le référencement du site

**Comment by vinyll** [comment]
A la modification d'une traduction, un editeur peut modifier **les traducteurs**.
Plusieurs traducteurs possible non limité à 1 seul, pas simplification de code (réutilisation de la fonctionnalité "auteurs" multiples)
