### ISSUE TITLE
Affichage du texte de la VO dans un draft traduction

### ISSUE THREAD

**Issue by kathakloss** [cafebabel/cafebabel.com#443]
Quand un traducteur clique sur 'Traduire cet article 'EN>FR' p.ex. pour 'réserver' sa traduction, il se retrouve ensuite sur des champs vides (donc il ne visualise plus la version originale du texte à traduire).

Solution: affichage de la version originale sur le draft traduction créé.

**Comment by ffameli** [comment]
solution a : le texte réapparait 
solution b : la trad vide s'ouvre dans un nouvel onglet / je peux jongler entre la page 1 et 2

**Comment by ffameli** [comment]
ouvrir un onglet = moins d'effets de bord
tester avec des éditeurs avec les deux solutions 
mais solution a pas triop compliquée non plus

**Comment by matthieuamare** [comment]
Solution A, clairement.
