### ISSUE TITLE
Attribut "hreflang" pour afficher l'URL qui correspond à une langue

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#454]
Dans la section <head> ajouter des éléments "link" qui renvoient vers les versions dans les autres langues.

Exemple Sur la page https://cafebabel.com/fr/article/catastrophe-une-nuit-dans-le-bouleversement-de-la-jeunesse-francaise-5ae00c07f723b35a145e82e5/ il faudrait trouver :

`<link rel="alternate" hreflang="it" href="https://cafebabel.com/it/article/catastrophe-la-nuova-voce-della-gioventu-francese-5ae00c12f723b35a145e838e/"/>`

**Comment by Aliocha-Iordanoff** [comment]
Petite précision : quand une URL est disponible dans plusieurs langues, chaque page doit identifier les différentes versions de langue, y compris la sienne.

**Comment by ffameli** [comment]
tache pour Johan

**Comment by johangiraud** [comment]
Où dois-je placer ceci : `<link rel="alternate" hreflang="it" href="https://cafebabel.com/it/article/catastrophe-la-nuova-voce-della-gioventu-francese-5ae00c12f723b35a145e838e/"/>` ? dans le `<header>` ?
@AliochaSemweb

**Comment by Aliocha-Iordanoff** [comment]
Non @cafebabel-webmaster !
Les éléments HTML "link" doivent se trouver dans l'en-tête. C'est à dire dans la section <head> du code HTML de la page, pas `<header>`.
Sachant qu'il faut bien retrouver dans le `<head></head>` une balise <link> par version linguistique incluant la page en cours.

**Comment by johangiraud** [comment]
oui dans la balise `<head>` pardon je me suis trompé.
J'ai pour l'instant `<link rel="alternate" hreflang={{ article.language }} href={{ article.detail_url }}"/>` qui donne par exemple `<link rel="alternate" hreflang="en" href="/en/article/about-us-5ad5d0474a66990451705d53/&quot;/">` pour l'article "about-us" Est-ce qu'il faut que j'aie le chemin absolu dans le href ou est-ce que le chemin relatif suffit ? @AliochaSemweb

**Comment by Aliocha-Iordanoff** [comment]
Il faut nécessairement une URL absolue dans cette balise @cafebabel-webmaster

**Comment by johangiraud** [comment]
ok

**Comment by johangiraud** [comment]
@vinyll pour obtenir une url absolue, je peux faire comment dynamiquement ?

**Comment by Aliocha-Iordanoff** [comment]
J'ai l'impression qu'il y a eu un début de travail sur ce sujet, car il y a une balise hreflang dans les entête, mais par contre il n'y a que la langue en cours qui est stipulée... 
exemple ici : https://cafebabel.com/fr/article/en-roumanie-des-citoyens-funky-contre-les-derives-du-gouvernement-5b05453af723b325c3728951/

Par ailleurs il y a un caractère étrange dans le html de la page, avec un /"/ en fin d'adresse >>>

![image](https://user-images.githubusercontent.com/14107448/40792745-f4c4e9d6-64fa-11e8-9383-25c710a2b65a.png)

**Comment by johangiraud** [comment]
Oui le caractère étrange est corrigé dans une branche pas encore mergé, pas d'inquiétude. Par contre oui j'ai mis l'attribut hreflang avec la langue en cours dans l'en-tête. Il faut autre chose donc ?

**Comment by Aliocha-Iordanoff** [comment]
Bien sûr @cafebabel-webmaster le but de cette balise est de lister toutes les versions disponible d'une même page dans différentes langues. 
cf. mes messages du 27/04. Il faut trouver dans l'entête autant de balises hreflang qu'il y a de langues accessibles.
Tu as toute l'explication ici !
https://support.google.com/webmasters/answer/189077?hl=fr

**Comment by johangiraud** [comment]
aaah d'accord @AliochaSemweb merci, je me pense là-dessus vite

**Comment by johangiraud** [comment]
>@vinyll pour obtenir une url absolue, je peux faire comment dynamiquement ?

@vinyll ?

**Comment by Aliocha-Iordanoff** [comment]
d'après la nomenclature que tu donnais plus haut @cafebabel-webmaster , il suffirait de mettre : 
`hreflang="{{ article.language }}"  href="https://cafebabel.com/{{ article.detail_url }}"`

**Comment by johangiraud** [comment]
merci @AliochaSemweb mais je n'aime pas trop mettre des choses en dur dans le code, si on change de modèle de domaine un moment, il faudra tout changer manuellement.. Mais bon je mets ça en attendant 👍

**Comment by Aliocha-Iordanoff** [comment]
Oui je vois @cafebabel-webmaster . J'espère néanmoins pour votre référencement naturel que vous n'allez pas changer de nom de domaine trop souvent :) !

**Comment by johangiraud** [comment]
certes 😆
