### ISSUE TITLE
Google Analytics vs Tag Manager

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#455]
Le site contient un conteneur Google Tag Manager, probablement issu de l'ancien site.

Questions : Tag Manager est-il utilisé ? Utile pour Café Babel ?

Problème : Les accès au compte Google tag Manager ne sont pas disponibles.
Préconisations : 
1/ Supprimer le Conteneur Googe Tag Manager.
2/ Insérer dans l'entête de la page le tracker asynchrone de Google Analytics :

**Comment by Aliocha-Iordanoff** [comment]
[tracker-GA.txt](https://github.com/cafebabel/cafebabel.com/files/1954792/tracker-GA.txt)

**Comment by Aliocha-Iordanoff** [comment]
@matthieuamare je te propose de poursuivre l'enquête pour retrouver votre compte Google Tag Manager, ce qui serait l'option la plus simple et techniquement la plus intéressante pour conserver l'historique du suivi sur Tag Manager, ce qui permettra de faire des comparaisons du nouveau site avec l'ancien, sur  des critères comportementaux notamment.

**Comment by matthieuamare** [comment]
@AliochaSemweb Je poursuis inlassablement mes efforts de recherche. Je viens d'avoir l'ancien DG au téléphone qui me confirme qu'il n'a jamais entendu parler de Google Tag Manager. Aurais-tu un identifiant ? Ou le moyen de savoir quelle adresse/id a été utilisé pour créer le compte ?

En parallèle, je poursuis mes recherches du côté des anciens webmaster... voire de l'ancien dev.

**Comment by Aliocha-Iordanoff** [comment]
Compte tag manger modifié si j'ai bien compris.
