### ISSUE TITLE
Paramétrage HTTPS / Google Analytics

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#456]
@matthieuamare 
Dans les paramètres de la propriété cafebabel.com de Google Analytics, il faut : 

- modifier le paramétrage par défaut popur préciser **https** et non pas **http** : https://analytics.google.com/analytics/web/?hl=fr&pli=1#/a126606w14777659p15593144/admin/property/settings

- supprimer le sous-domaine www. qui n'est pas utilisé pour le nouveau site.

![image](https://user-images.githubusercontent.com/14107448/39359268-a27f1b98-4a19-11e8-94c2-267d645c6cd9.png)

**Comment by matthieuamare** [comment]
Done :)
