### ISSUE TITLE
Bouton de partage Twitter utilise le compte_EN sur la version FR du site

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#457]
Le bouton de partage Twitter sur la version /fr/ du site fait mention du profil https://twitter.com/cafebabel_ENG , alors qu'il faudrait logiquement qu'il mentionne https://twitter.com/cafebabel_FR

**Comment by Aliocha-Iordanoff** [comment]
Préco : il faudrait que le bouton de partage tienne compte de la langue pour mentionner le compte Twitter correspondant.

**Comment by johangiraud** [comment]
weird, je vois pour la version française (https://cafebabel.com/fr/) que le bouton de partage (celui en haut à droite) pointe bien vers https://twitter.com/cafebabel_FR. Peux-tu m'expliquer ? ou m'envoyer une capture d'écran du problème @AliochaSemweb ?

**Comment by Aliocha-Iordanoff** [comment]
![image](https://user-images.githubusercontent.com/14107448/39827115-358c416c-53b7-11e8-9e42-9073983384b3.png)
Je parle du lien de partage en pied d'article. @cafebabel-webmaster 

Le bouton en haut à droite n'est pas un bouton de partage mais juste un lien vers le profil Twitter. Celui-ci est bien réglé sur les bonnes langues respectives.

**Comment by johangiraud** [comment]
Ok got it. @vinyll je peux obtenir l'adresse twitter de chaque version linguistique via `{{ social_network_url_for('twitter') }}`. Mais comment obtenir seulement l'id = @cafebabel_ENG ?

**Comment by vinyll** [comment]
Je dirais que pour être autonome tu peux faire:
```
{% set lang = current_language() %}
{% if lang == 'en' %}{% set twitter_nickname = 'cafebabel_ENG' %}{% endif %}
{% if lang == 'fr' %}{% set twitter_nickname = 'cafebabel_FRE' %}{% endif %}
…
```

**Comment by johangiraud** [comment]
Ok, merci beaucoup !

**Comment by johangiraud** [comment]
arf j'ai
```
<nav class=share>
  <p>Loved this story? Then tell your friends:
    {% set lang = current_language() %}
    {% if lang == 'en' %}{% set twitter_nickname = 'cafebabel_ENG' %}{% endif %}
    {% if lang == 'fr' %}{% set twitter_nickname = 'cafebabel_FR' %}{% endif %}
    {% if lang == 'de' %}{% set twitter_nickname = 'cafebabel_DE' %}{% endif %}
    {% if lang == 'it' %}{% set twitter_nickname = 'cafebabel_IT' %}{% endif %}
    {% if lang == 'es' %}{% set twitter_nickname = 'cafebabel_ES' %}{% endif %}
    {% if lang == 'pl' %}{% set twitter_nickname = 'cafebabel_POL' %}{% endif %}
    <a href="https://twitter.com/share?url={{ request.url|quote_plus }}&text={{ article.title }}&via={{ twitter_nickname }}">Twitter</a>
    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.url|quote_plus }}">Facebook</a>
  </p>
  </nav>
```
mais j'obtiens une erreur : `TypeError: 'str' object is not callable`
J'ai dû oublier quelque chose mais je ne sais pas quoi @vinyll

**Comment by davidbgk** [comment]
`{% set lang = current_language() %}` devrait être `{% set lang = current_language %}`

**Comment by johangiraud** [comment]
j'essaie, merci !

**Comment by johangiraud** [comment]
Bon je ne peux pas tester à cause de ce problème mais je n'ai plus d'erreur en tout cas, donc je pense que c'est bon 😄 

Pour réparer le test `test_published_article_should_display_content` dans `test_article.py` j'essaie de remplacer la valeur `cafebabel_ENG` par `{twitter_nickname}` mais je ne sais pas où définir cette variable dans le test. @davidbgk @vinyll
