### ISSUE TITLE
Rendre privé les drafts traductions 

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#458]
Exemple : https://cafebabel.com/fr/article/catastrophe-une-nuit-dans-le-bouleversement-de-la-jeunesse-francaise-5ae00c07f723b35a145e82e5/ 
Sur cette page, seule la pastille "IT" est verte, les autres ne sont pas cliquables. ok.

**Mais!**
En pied de page, on trouve 👍 
*Review this article in: es: [spa] Catastrophe o la metamorfosis de la juventud francesa*
Qui pointe sur : https://cafebabel.com/es/article/translation/5ae00c08f723b35a145e82f0/

3 Questions : 
- pourquoi le bouton "ES" n'est pas actif en haut de la page ?
- Pourquoi l'URL contient un /translate/ alors que la version italienne n'en contient pas ?
- pourquoi la fin de cette URL n'est pas réécrite ?

**Comment by matthieuamare** [comment]
Review this article ne doit être visible que pour les éditeurs. Et le genre d'articles dont tu parles type (https://cafebabel.com/es/article/translation/5ae00c08f723b35a145e82f0/) ne doit pas apparaître en ligne, ni en bas d'article.

**Comment by matthieuamare** [comment]
Johan peut cacher le lien aux visiteurs. Mais est-ce un souci sur le plan de référencement de laisser cette url en ligne ?

**Comment by Aliocha-Iordanoff** [comment]
Si cet article n'est pas sensé être visible des visiteurs, il ne faut surtout pas permettre à Google d'y accéder, sinon il va naturellement le référencer et potentiellement conduire des internaute vers lui. @matthieuamare

**Comment by ffameli** [comment]
solution a : rendre invisible le lien
solution b : ne rendre la traduction en cours en bas d'article visible uniquement pour les éditeurs et le tradcuteur concerné

**Comment by Aliocha-Iordanoff** [comment]
Comme l'URL change lors de la publication de la traduction, il ne faut pas la laisser se faire indexer par Google.  Si jamais cette page doit rester accessible publiquement, il faut penser à mettre automatiquement en entête une balise robot noindex nocache. @ffameli 

De mon point de vu la solution B est la meilleure.

**Comment by ffameli** [comment]
solution : no follow pour cette page
vérifier qui peut modifier la traduction en cours
identifier qui pourrait modifier la trad en cours ou alors renvoyer la traduction en cours dans le profil : trouver une solution élégante

**Comment by Aliocha-Iordanoff** [comment]
Idéalement il faudrait plutôt un no-index sur ces pages.
Un no-follow sur le lien pourrait protéger de l'indexation les nouvelles pages, mais pas celle qui sont déjà référencées @ffameli

**Comment by matthieuamare** [comment]
Johan voudrait donner la possibilité aux traducteurs de retrouver son travail en cours via une pastille couleur pour le moment accessibles uniquement aux éditeurs (lié à #487). Autre issue ?

**Comment by vinyll** [comment]
Quand une traduction est en "draft", il y a une meta balise "no-index" sur cette traduction.

**Comment by ffameli** [comment]
rendre visible la trad en cours uniquement pour le traducteur qui a réservé la trad et les éditeurs

**Comment by vinyll** [comment]
Un draft de traduction reste privé, lisible par le traducteur ou les editeurs uniquement
