### ISSUE TITLE
Redirections des rubriques & sous-rubriques

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#463]
Quel est le schéma de redirections prévu pour les pages des rubriques thématiques prévues dans les anciens sites ?

Ex : http://www.cafebabel.fr/societe/ecologie/
ou : http://www.cafebabel.fr/societe/

Ces pages sont importantes à bien rediriger vers des pages sas équivalentes pour le référencement naturel.

**Comment by Aliocha-Iordanoff** [comment]
@pointbar tu es peut-être en mesure de me répondre ?

**Comment by matthieuamare** [comment]
Pas très grave.

**Comment by Aliocha-Iordanoff** [comment]
problem solved
