### ISSUE TITLE
Rajouter prenom nom dans l'url des profils

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [cafebabel/cafebabel.com#465]
- Réécrire l'URL des pages des auteurs.
- Donner un titre à cette page par l'insertion d'une balise >TITLE>

Exemple : https://cafebabel.com/fr/profile/5ae00444f723b35a145d71dc/

**Comment by ffameli** [comment]
préconisation : tout traduire

**Comment by ffameli** [comment]
meilleur réf. si nom auteur visible

**Comment by ffameli** [comment]
traduire "profile"

**Comment by ffameli** [comment]
bonus : texte de présentation de l'auteur

**Comment by matthieuamare** [comment]
Scopyleft l'explique en affirmant s'inspirer de Medium. Or, sur Medium l'écriture des URL de profil sont les suivantes  https://medium.com/@MITTechReview.

Donc avec un @ et sans ID (chiffres & lettres).

Des idées @pointbar @davidbgk @vinyll ?

**Comment by Aliocha-Iordanoff** [comment]
Pas exactement @matthieuamare 
@pointbar nous disait que l'inspiration venant de Medium concerne les articles. Sur Medium, les articles ont effectivement un ID dans l'URL : https://medium.com/mit-technology-review/lets-destroy-bitcoin-3211861ce7a3 (ainsi qu'une thématique en premier sous-dossier)

L'idée d'insérer un @ devant le nom du profil auteur permet de faire un lien intuitif avec le compte Twitter de l'auteur : 
https://eand.co/@umairh >> https://twitter.com/umairh

Ce n'est pas la même stratégie que d'écrire en toutes lettre le nom de l'auteur dans l'URLs.

Si tous vos auteurs sont actifs sur Twitter, l'option "Medium" est intéressante. Sinon, je vous préconise le nom en toutes lettres avec des tirets comme séparateurs.

**Comment by matthieuamare** [comment]
Pour le remplacement du chiffrement par le nom de l'auteur. À voir ce que ça coûte en dev.

**Comment by ffameli** [comment]
sécuriser les profils sans chiffrement  : éviter les homonymes

**Comment by ffameli** [comment]
Solution : rajouter nom/prenom auteur
Question : enleve t on l'id ou pas ?

**Comment by Aliocha-Iordanoff** [comment]
idéalement oui @ffameli l'ID dans l'URL n'apporte rien à l'internaute ni à google. Donc il est préférable de l'enlever.

**Comment by ffameli** [comment]
solution : p pour profil + prenom nom + id

**Comment by Aliocha-Iordanoff** [comment]
je pense qu'il vaut mieux conserver  /profil/ ou /auteur/ plutôt que /p/
Pour la suite du slug, oui ok pour /prenom-nom-ID

**Comment by matthieuamare** [comment]
Supprimer le terme profile. Voir si c'est coûteux lors du traitement de l'issue sur la suppression de /article #464

**Comment by johangiraud** [comment]
Hello @vinyll, sur cafebabel.com, mon profil ne contient toujours uniquement qu'un id : https://cafebabel.com/fr/profile/5ae0047ff723b35a145da194/ est-ce normal ?

**Comment by vinyll** [comment]
@cafebabel-webmaster oui, c'est à tester en pre-production

**Comment by johangiraud** [comment]
d'acc 😇 yeah sur preprod : https://preprod.cafebabel.com/en/profile/johan-giraud-5adfa6c5f723b33272952afa/ 🎉

**Comment by vinyll** [comment]
fixed
