### ISSUE TITLE
Erreur 500 sur l'ajout d'un tag (version FR)

### ISSUE THREAD

**Issue by matthieuamare** [cafebabel/cafebabel.com#472]
Quand je veux classer les articles en y ajoutant des tags et **que je ne suis pas l'auteur de l'article**, lorsque je sauvegarde l'article je tombe sur une erreur 500. (effet de bord du dernier réimport puisqu'avant l'issue n'existait pas)

**Comment by vinyll** [comment]
En rapport avec https://github.com/cafebabel/cafebabel.com/issues/440

**Comment by ffameli** [comment]
tous les tags de la version française uniquement sont concernés

**Comment by matthieuamare** [comment]
@pointbar et François ou Matthieu discute d'une possible réparation sans passer par sprint ou presta.
