### ISSUE TITLE
Tag "Creative" et "Experience" ne fonctionnent pas dans la FR

### ISSUE THREAD

**Issue by matthieuamare** [cafebabel/cafebabel.com#481]
Quand je veux ajouter un tag "Creative" ou "Experience" dans un article où je ne suis pas l'auteur, je tombe sur une erreur 500. Donc contrainte forte pour le classement des articles. 

Cela marche pour toutes les autres versions.

**Comment by ffameli** [comment]
vérifier si le bug est sur pré prod ou cafebabel.com

**Comment by matthieuamare** [comment]
cafebabel.com

**Comment by ffameli** [comment]
demander à Johan de tager autrement Creative et que ce soit éditorialisé normalement, par exemple _creative pour débloquer la situation

**Comment by ffameli** [comment]
identifier d'où vient le bug exacement : reprendre les articles tagé creative et enlever le tag pour voir l'effet - enlever et remettre un par un pour voir si le bug persiste

**Comment by matthieuamare** [comment]
Un seul article est pour l'instant taggé "Creative". Je ne peux d'ailleurs pas enlever le tag. Le problème persiste sur tous les autres. Ne pas oublier le tag "Experience" qui cause le même problème.

**Comment by matthieuamare** [comment]
Fonctionne effectivement dans la pre-prod.

**Comment by matthieuamare** [comment]
Un réimport pourrait-il solutionner le problème ? Possible de ne le faire que pour la page fr @vinyll ?

**Comment by ffameli** [comment]
faire remonter les url pour qualifier le bug le plus possible (sur quel profil le bug apparait ? )
merci d'identifier 5 url environ ci dessous @cafebabel-webmaster @matthieuamare

**Comment by johangiraud** [comment]
avec mon profil (https://cafebabel.com/fr/profile/5ae0047ff723b35a145da194/) dans la version française, si j'essaie de tagger cet article https://cafebabel.com/fr/article/5ae32b4df723b358bd2035fa/edit/ avec le tag _Experience_ ou _Creative_ j'ai une erreur 500
De même pour ces articles https://cafebabel.com/fr/article/5af06b04f723b358bd203618/edit/, https://cafebabel.com/fr/article/5ae00c07f723b35a145e82e5/edit/, https://cafebabel.com/fr/article/5ae00c0df723b35a145e833d/edit/, https://cafebabel.com/fr/article/5ae00c09f723b35a145e830c/edit/

**Comment by ffameli** [comment]
il  y a une erreur 500 pour le tag Immigration (nouveau) en Français
Il est également impossible d'enlever des vieux tags comme Mind the Gap sur la VF

**Comment by ffameli** [comment]
attention à ne pas mettre d'espace à la fin des tags
