### ISSUE TITLE
notifier à l'éditeur qu'une traduction vient d'être créée dans sa langue

### ISSUE THREAD

**Issue by ffameli** [cafebabel/cafebabel.com#482]
prévenir qu'une nouvelle traduction est arrivée, par mail, comme pour les pitchs

**Comment by ffameli** [comment]
vérifier quelles infos doivent arriver par mail @matthieuamare (la liste des éditeurs par langue existe déjà)

**Comment by vinyll** [comment]
pas d'envoi de mail en cas de modification.
