### ISSUE TITLE
Permettre de supprimer un article pour les éditeurs DE, EN, IT

### ISSUE THREAD

**Issue by ffameli** [cafebabel/cafebabel.com#490]
Impossible pour ces éditeurs de supprimer un article --> message "unauthorized"
Apparement cela fonctionne sur le preprod

**Comment by ffameli** [comment]
recenser les url sur lesquels cela ne marche pas
cela concerne t il des nouveaux articles ou des articles importés ?

**Comment by ffameli** [comment]
merci de copier coller ci dessous env 5 url avec ce problème @cafebabel-webmaster @matthieuamare

**Comment by larabullens** [comment]
Pour la version anglaise: 
- https://cafebabel.com/en/article/lalala-5af986a7f723b3596e100a8d/
- https://cafebabel.com/en/article/not-our-president-womens-marches-across-europe-5ae00b94f723b35a145e7a9c/
- https://cafebabel.com/en/article/matteo-renzi-all-in-for-italys-risky-referendum-5ae00b7ef723b35a145e7922/
- https://cafebabel.com/en/article/god-save-gina-miller-5ae00b71f723b35a145e7842/
- https://cafebabel.com/de/article/paris-ein-paar-tage-dann-ist-das-camp-zuruck-5ae00b6bf723b35a145e77da/

**Comment by kathakloss** [comment]
Pour la version DE le message suivant s'affiche en supprimant un article:

Unauthorized
The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

Des exemples en Allemand que j'ai tenté de supprimer:

https://cafebabel.com/de/article/ein-neuer-artikel-auf-deutsch-5af971b2f723b3596e100a8b/
https://cafebabel.com/de/article/madrid-die-vergessenen-millennials-von-vallecas-5ae32b99f723b358bd2035fb/
https://cafebabel.com/de/article/ger-larme-des-mots-les-activistes-de-linfo-en-europe-de-lest-5ae00c16f723b35a145e83c9/
https://cafebabel.com/de/article/5ae00c0af723b35a145e8314/

**Comment by larabullens** [comment]
L'outil 'supprimer un article' fonctionne pour la version IT

**Comment by vinyll** [comment]
@larabullens: J'ai pu supprimer https://cafebabel.com/en/article/god-save-gina-miller-5ae00b71f723b35a145e7842/
Est-ce que tu peux re-tenter de ton côté de supprimer ces articles _stp_ pour valider que le bug est toujours présent ?

**Comment by larabullens** [comment]
@vinyll Je ne trouve pas l'article en haut (erreur 404) que t'as supprimé. 

Par contre, j'ai essayé de supprimer cet article: https://cafebabel.com/en/article/transnistria-bringing-change-one-hostel-at-a-time-5afd3d3df723b325c3728917/

Et ça ne marche pas. J'ai toujours le message "unauthorized"

**Comment by vinyll** [comment]
Tu ne trouves pas l'article, parce qu'il est supprimé ! ;)
J'ai testé celui que viens d'envoyer, et j'ai pu l'effacer aussi.

Je te contacte par Slack…
