### ISSUE TITLE
Le tag Impact donne une erreur 500 en ES

### ISSUE THREAD

**Issue by ffameli** [cafebabel/cafebabel.com#491]
impossible pour l'éditeur ES de tagger un article impact sur cadebabel.com mais fonctionne dans le preprod

**Comment by ffameli** [comment]
qualifier le bug au mieux pour éviter un temps de recherche des éditeurs : faire remonter les url - reproduire le bug pour comprendre d'où vient le problème
merci de copier collet ci dessous env 5 url avec ce problème @cafebabel-webmaster @matthieuamare

**Comment by matthieuamare** [comment]
Voici :
- https://cafebabel.com/es/article/friganismo-en-la-basura-tambien-hay-manjares-5ae00c07f723b35a145e82dc/
- https://cafebabel.com/es/article/vegano-y-feminista-asi-es-el-mundo-de-sophia-hoffman-5ae00c0df723b35a145e8339/
- https://cafebabel.com/es/article/es-el-boicot-la-solucion-al-poder-desenfrenado-5ae00c08f723b35a145e82f4/
- https://cafebabel.com/es/article/florian-nock-el-hombre-que-amaba-a-los-insectos-5ae00c00f723b35a145e8284/
- https://cafebabel.com/es/article/the-woman-behind-una-camarera-contra-los-estereotipos-5ae00bfbf723b35a145e8210/

**Comment by vinyll** [comment]
voir #481

**Comment by vinyll** [comment]
fixed in #498
