### ISSUE TITLE
Pb de contraste dans le header

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#80]
- Page: /
- Type : UX - accessibilité
- Problème : Le logo café Babel et le hamburger menu sont très peu visible.
- Exemple d'amélioration : revoir le contraste : https://leaverou.github.io/contrast-ratio/

**Comment by johangiraud** [comment]
c'est susceptible d'évoluer, ça fait partie des inconvénients de dessiner au fur et à mesure, c'est assez compliqué pour moi d'avoir une vue d'ensemble.
