### ISSUE TITLE
Manque des métas

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#82]
- Page : /
- Type : UX - Référencement
- Problèmes : manque des éléments : favicon, meta description, twitter:description
- Exemple de solutions : placer les éléments à exposer dans le DoD. Prendre contact avec https://www.semaweb.fr/

**Comment by johangiraud** [comment]
ok

**Comment by johangiraud** [comment]
à mettre dans une US ultérieure

**Comment by johangiraud** [comment]
#70 + #9

**Comment by davidbgk** [comment]
@cafebabel-webmaster Est-ce qu'il y a une limite sur la taille du résumé d'un article ? C'est pour savoir si on doit tronquer

**Comment by davidbgk** [comment]
@cafebabel-webmaster est-ce qu'il serait possible de préciser les informations souhaitées parmi celles-ci https://gethead.info/#social ?

**Comment by johangiraud** [comment]
Pour la limite de taille, pour la méta description, on devrait être autour des 160 caractères. Mais parfois le chapô sera plus long donc tant pis. C'est le comportement par défaut, à terme il faudrait pouvoir personnaliser cette méta description si celle créée grâce au chapô n'est pas parfaite. Mais plus tard.

**Comment by johangiraud** [comment]
On a besoin des meta de facebook, twitter, g+, pas de précision quant à pinterest, on peut pinter des trucs à partir de cafébabel.com sans problème. Pour les Instant Articles, on voudrait aller vers ça, au moins pour vérifier les différences de performances et surtout les incidences sur le traffic. Donc il faut que je me penche sur ça côté facebook app mais au niveau des méta oui, mettons-nous toutes les cartes en main pour que ça fonctionne. @davidbgk

**Comment by davidbgk** [comment]
@cafebabel-webmaster est-ce que du coup tu pourrais t'en charger ?

**Comment by johangiraud** [comment]
Ok je m'en charge avec @pointbar

**Comment by pointbar** [comment]
Ok now
