### ISSUE TITLE
Info-bulle fixe

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#86]
Page : /article/proposal/new/
Type : UX
Contexte : Lorsque je valide le formulaire ; quand un champ obligatoire n'est pas rempli alors une info-bulle s'affiche - "Veuillez compléter ce champ"
Problème : Lorsque je "scroll", l'info-bulle reste fixe dans la page.

**Comment by davidbgk** [comment]
Il s'agit très certainement d'un bug navigateur…

**Comment by pointbar** [comment]
@davidbgk oui, je ferme.
