### ISSUE TITLE
issue - US#0 Doit comporter le nom et prénom

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#93]
**Page** : /profile
**Type** : Fonctionnel
**Contexte** : D'après US0 #8 - le formulaire -profile- doit comporter le nom/prénom.
**Problème**: Le formulaire ne comporte pas le nom/prénom.

**Comment by vinyll** [comment]
Il avait été proposé de faire un formulaire minimaliste pour l'inscription, et une invitation à l'enrichissement des infos dans le profil.
@cafebabel-webmaster : une opinion ?

**Comment by pointbar** [comment]
@vinyll - j'ai changé l'url /register par /profile

**Comment by johangiraud** [comment]
Oui je pense qu'il faut ajouter nom et prénom à l'inscription : du coup le _formulaire minimaliste_ sera constitué par : 
- prénom
- nom
- email
- mot de passe
Et ensuite lorsqu'on se rend sur le profil, on peut accéder aux infos supplémentaires. Good ?

**Comment by vinyll** [comment]
@davidbgk: tu suggérais de plutôt renseigner un _full name_ plutôt qu'un nom + prénom. Des retours à ce sujet ?

**Comment by johangiraud** [comment]
oui ou le full name, c'est juste que j'aurais préféré voir écrit : _Johan's profile_ plutôt que _Johan Giraud's profile_

**Comment by davidbgk** [comment]
https://n.survol.fr/n/naming-conventions-in-europe-asia-and-north-africa

https://www.w3.org/International/questions/qa-personal-names

**Comment by johangiraud** [comment]
on conserve un seul champ : _full name_ pour se présenter. Doit être éditable dans la partie éditable du profil

**Comment by pointbar** [comment]
je peux clôturer cette issue @cafebabel-webmaster

**Comment by johangiraud** [comment]
ça peut être fermé si on fait référence à #132 et à #207
