### ISSUE TITLE
issue - US#8 info-bulles en supperposition

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#95]
**Page** : /login
**Type** : UX
**Contexte** : Si je rentre de mauvaise information de login et que j'ouvre le menu hamburger, l'info-bulle apparait au premier plan . Testé sur Safari et FF

**Comment by johangiraud** [comment]
L'info-bulle apparaît bien *dessous* le menu-burger. Par contre on a une superposition au niveau de l'adresse (si on rentre une mauvaise adresse) et le `label`. Tu as ça aussi ? @pointbar

**Comment by vinyll** [comment]
Un screenshot à partager @pointbar ?

**Comment by pointbar** [comment]
@vinyll - ![95](https://user-images.githubusercontent.com/451908/34156520-e2032e38-e4bd-11e7-8403-3a26455b7ab5.png)

**Comment by johangiraud** [comment]
Ok weird, sur safari et FF donc ?

**Comment by pointbar** [comment]
@cafebabel-webmaster au moins sur Safari et FF

**Comment by johangiraud** [comment]
@pointbar ce problème persiste ?

**Comment by pointbar** [comment]
Non ok @cafebabel-webmaster
