### ISSUE TITLE
issue - US#0 je ne peux pas gérer mon profil.

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#96]
**Page** : /profile
**Type** : fonctionnel
**Contexte** : 
1- le bouton -save my profile- renvoi sur une page d'erreur (405) -Method Not Allowed-
2- les champs ne sont accessibles à l'édition

**Comment by vinyll** [comment]
Corrigé lors de la PR sur le passage edit-in-place => consultation/edition du profil.
