### ISSUE TITLE
issue - US8 je suis connecté ?

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#97]
Page : /
Type : UX
Contexte : D'après l'US8 #22 j'ai l'impression que -doit me signifier que je suis connecté- signifie que sur les différentes pages du site, je sais que je suis connecté.
Problème : Après un -login- sur les autres pages que -profile- je n'ai pas d'indication de log.

**Comment by johangiraud** [comment]
On traitera la notification de connexion ici : #23 dans le sprint5

**Comment by pointbar** [comment]
Ok @cafebabel-webmaster
