### ISSUE TITLE
issue - US20 - Email d'une éditrice

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#98]
**Page** : http://127.0.0.1:5000/article/proposal/new/
**Type** : Fonctionnel
**Problème** :
  - doit comporter un lien vers un contact email vers une éditrice
  - je ne vois pas le mail de l'éditrice.

**Comment by johangiraud** [comment]
je m'en occupe

**Comment by johangiraud** [comment]
Pour l'instant il y a uniquement le mail générique : editors@cafebabel.com

**Comment by johangiraud** [comment]
ok done ! :-)
