### ISSUE TITLE
issue - US20 - Soumission de l'article

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#99]
Page : /article/proposal/new/ (anonyme)
Type : Fonctionnel
Problème : À la soumission, ça semble charger, mais rien ne se produit.

**Comment by davidbgk** [comment]
It looks to be an issue related to the mail server configuration that was has been fixed since then, can you retry @pointbar ?

**Comment by pointbar** [comment]
It works now - @davidbgk
